site:
  name: Dra. Isadora Rosa
  site: 'https://phamaralbr.github.io'
  base: '/dra-isadora-rosa'
  trailingSlash: false

  googleSiteVerificationId: false

# Default SEO metadata
metadata:
  title:
    default: Dra. Isadora Rosa | Ginecologia e Reprodução Humana em Brasília DF
    template: 'Dra. Isadora Rosa | Ginecologia e Reprodução Humana em Brasília DF'
  description: 'Especialista em Ginecologia e Reprodução Humana em Brasília DF. Atendimento humanizado, exames, tratamentos e acompanhamento completo. Agende sua consulta.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Dra. Isadora Rosa
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
    profile:
      username: 'isadorarosa'
  twitter:
    cardType: summary_large_image

i18n:
  language: pt-BR
  textDirection: ltr

analytics:
  vendors:
    googleAnalytics:
      id: 'G-Y8983XJSGX'

ui:
  theme: 'light:only' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
